apiVersion: apps/v1
kind: Deployment
metadata:
  name: coit-frontend
  labels:
    app: coit-frontend
spec:
  selector:
    matchLabels:
      app: coit-frontend
  replicas: 3
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: coit-frontend
    spec:
      containers:
      - image: dockerkittu/coit-frontend:ORG1
        imagePullPolicy: IfNotPresent
        name: coit-frontend
        env:
          - name: SA_LOGIC_API_URL
            valueFrom:
              configMapKeyRef:
                name: coit-frontend-config
                key: python_url
          - name: SMS_PROVIDER_API_URL
            valueFrom:
              configMapKeyRef:
                name: coit-frontend-config
                key: sms_provider
          - name: SMS_PROVIDER_USERNAME
            valueFrom:
              secretKeyRef:
                name: coit-frontend-secrets
                key: username
          - name: SMS_PROVIDER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: coit-frontend-secrets
                key: password
        ports:
          - containerPort: 8080