apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./coit-backend1-deployment.yaml
- ./coit-backend1-service.yaml
images:
- name: dockerkittu/coit-frontend
  newTag: ORG1

configMapGenerator:
- name: coit-frontend-config
  envs:
  - application.properties

secretGenerator:
  - name: coit-frontend-secrets
    envs:
    - applicationsecrets.properties

commonLabels:
  app: coitfrontend
  managed-by: kustomize

labels:
  - pairs:
      location: mumbai
