apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

images:
  - name: dockerkittu/coit-backend1
    newName: dockerkittu/coit-backend1
    newTag: ORG1

namespace: local